version: "3"
includes:
  fmt: ./scripts/fmt.yml
  lint: ./scripts/lint.yml
tasks:
  clean:
    desc: Remove nix build artifacts
    cmds:
      - rm -rf result
  push:shell:cache:
    desc: Update Cachix for development shell
    cmds:
      - nix-build ./shell.nix | cachix push gotrade-home-manager-shell
  push:cache:
    desc: Update Cachix
    cmds:
      - nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push gotrade-home-manager
      - nix build --impure --json $HOME/gotrade-home-manager#homeConfigurations.$USER.activationPackage | jq -r '.[].outputs | to_entries[].value' | cachix push gotrade-home-manager
  lint:
    desc: Lint all files
    cmds:
      - task: lint:sh
  fmt:
    desc: Format all files
    cmds:
      - task: fmt:sh
      - task: fmt:yaml
      - task: fmt:nix
      - task: fmt:md
  cfg:scripts:
    cmds:
      - chmod -R +x ./scripts
